# Application Configuration Properties
spring.application.name=Quantity Measurement App
server.port=8080

# Repository Type Configuration either "cache" or "database"
repository.type=database

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Database (Development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# Logging Configuration
logging.level.root=INFO
// logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Enable request details logging
spring.mvc.log-request-details=true

# Enable resolved exception logging
spring.mvc.log-resolved-exception=true

# Logging levels
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.servlet.mvc=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Your application logging
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.com.example.personrestapi=DEBUG

# Custom log pattern for console output to include timestamp, logger name, and message
# The pattern includes:
# %d{yyyy-MM-dd HH:mm:ss} - Timestamp in the format of year-month-day hour:minute:second
# %logger{36} - Logger name truncated to 36 characters
# %line - Line number where the log statement was issued
# %msg%n - The log message followed by a new line
# console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%thread] [%logger{5}:%line] %msg%n"
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{5}:%line - %msg%n

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.info.enabled=true